---
- name: Install The "{{ software_name }}" package
  yum:
    name : "{{ pkg_name }}"
    state : present

- name: Copy a file for the content
  copy:
    src: nidhi.html
    dest: "{{ location }}"

- name : writing a content
  copy : 
   content: "Hello from ansiblke galaxy"
   dest : "{{ location }}"/Nidhi.html
  notify: Restart service
